### ISSUE TITLE
Список не полный? (№755/1439/16-к и 757/3623/20-к)

### ISSUE THREAD

**Issue by zer0init1** [uablacklist/uablacklist.net#4]
Часть доменов\сетей нет в списке. Например те которые были приняты в блокировку в 2020 по решениям №755/1439/16-к и 757/3623/20-к. НКРСИ: https://nkrzi.gov.ua/index.php?r=site/index&pg=99&id=1872&language=ru

Как пример это:
- favbet1.com
- joykasino.net
- uafavorit77.com

В целом список есть на фолбэк заглушке провайдера Триолан по ссылке: http://blocked.triolan.com.ua/
LG: http://lg.triolan.net.ua/

P.S: Могу помочь докинуть домены если что и закинуть PR

**Comment by pfactum** [comment]
Нове:

https://nkrzi.gov.ua/index.php?r=site%2Findex&pg=99&id=2053&language=uk

**Comment by zer0init1** [comment]
> Нове:
> 
> https://nkrzi.gov.ua/index.php?r=site%2Findex&pg=99&id=2053&language=uk

Уже не актуально. Закрыли дело и блокироваться не будут. https://nkrzi.gov.ua/index.php?r=site/index&pg=99&id=2056&language=uk

**Comment by uablacklist** [comment]
> https://nkrzi.gov.ua/index.php?r=site/index&pg=99&id=1872&language=ru

они в итоге его отменили:
https://nkrzi.gov.ua/index.php?r=site/index&pg=99&id=1877&language=uk
https://nkrzi.gov.ua/index.php?r=site/index&pg=99&id=1919&language=ru
