### ISSUE TITLE
В списке нет сайтов из указа №109/2021 

### ISSUE THREAD

**Issue by asavah** [uablacklist/uablacklist.net#6]
Отсутсвуют сайты из указа https://www.president.gov.ua/documents/1092021-37481 от 23/03/2021

**Comment by uablacklist** [comment]
Готово https://github.com/uablacklist/uablacklist.net/commit/ba50b51294fd3afefd54922ec0f997688d7b3924

**Comment by asavah** [comment]
Благодарю.
